apiVersion: apps/v1
kind: Deployment
metadata:
  name: bull-board
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bull-board
  template:
    metadata:
      labels:
        app: bull-board
    spec:
      containers:
        - name: bull-board
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST }}
            - name: REDIS_PORT
              value: "{{ .Values.env.REDIS_PORT }}"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
