replicaCount: 1

image:
  repository: deadly0/bull-board
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: bull-board-service
  type: LoadBalancer
  port: 80
  targetPort: 3000
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "your-certificate-id"  # Replace with your actual certificate ID
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - bullboard.outlines.info
    - www.bullboard.outlines.info
  redirectHost: https://www.bullboard.outlines.info
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.bullboard.outlines.info"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: bullboard-info-tls

env:
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
