replicaCount: 1

image:
  repository: sazzeb/checklist-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: checklist-back-service
  type: LoadBalancer
  port: 80
  targetPort: 9009
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "your-certificate-id"  # Replace with your actual certificate ID
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - outlines.info
    - www.outlines.info
  redirectHost: https://www.outlines.info
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://www.outlines.info"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
    enabled: true
    secretName: outlines-info-tls
